In [3]:
import pandas as pd
import numpy  as np
import math

In [57]:
objs = pd.read_csv("./proto_resultfinal.csv",header=None)
objs = objs.drop(columns=[0,2])
objs = objs.drop(index=0)
objs = objs.drop_duplicates()
# objs.to_csv("./objfinal.csv")
obj = objs.to_numpy(dtype=np.float64)

In [34]:
max_mass = max(obj[:,0])
min_mass = min(obj[:,0])
max_load = max(obj[:,1])
min_load = min(obj[:,1])
obj[:,0] = (obj[:,0]-min_mass)/(max_mass-min_mass)
obj[:,1] = (obj[:,1]-min_load)/(max_load-min_load)

In [35]:
obj[obj[:,0] ==0] = np.array([1e-8,1e-8]) 
obj

array([[1.00000000e-08, 1.00000000e-08],
       [1.07825930e-01, 1.41304305e-01],
       [2.62389839e-01, 3.57158913e-01],
       [7.31214379e-02, 9.24773327e-02],
       [5.01294953e-01, 5.97800629e-01],
       [1.48886607e-01, 1.91085691e-01],
       [5.43588616e-02, 5.24918498e-02],
       [1.15458697e-01, 1.47275710e-01],
       [1.20616219e-02, 4.53922494e-03],
       [7.48708510e-01, 8.30775174e-01],
       [2.21199047e-01, 2.97738961e-01],
       [1.96365832e-01, 2.76643031e-01],
       [1.44419313e-01, 1.88273829e-01],
       [2.70785883e-01, 3.65454737e-01],
       [2.41233139e-02, 9.39201243e-03],
       [4.58932410e-01, 5.44562749e-01],
       [8.44628996e-01, 8.94514706e-01],
       [1.84304201e-01, 2.32314199e-01],
       [4.06536505e-01, 4.76519664e-01],
       [6.65399054e-01, 8.06439158e-01],
       [2.49526569e-01, 3.45897534e-01],
       [5.31062608e-01, 6.55748064e-01],
       [8.48557746e-01, 9.28383879e-01],
       [3.64286329e-01, 4.53666751e-01],
       [6.150229

In [36]:
q = np.zeros((obj.shape))
for i in range(obj.shape[1]):
    sum = np.sum(obj[:,i])
    for j in range(obj.shape[0]):
        q[j,i] = obj[j,i]/(sum-obj[j,i])

In [37]:
l = np.zeros(2)
l[0] = np.sum(q[:,0]*np.log(q[:,0]))
l[1] = np.sum(q[:,1]*np.log(q[:,1]))

In [41]:
l = -l/np.log(2)

In [42]:
w = np.zeros(2)

In [43]:
w[0] = (1-l[0])/(2-l[0]-l[1])

In [44]:
w[1] = (1-l[1])/(2-l[0]-l[1])

In [45]:
w

array([0.49861004, 0.50138996])

In [46]:
h = np.zeros((obj.shape))

In [47]:
for i in range(h.shape[1]):
    for j in range(h.shape[0]):
        h[j,i] = q[j,i]*w[i]

In [68]:
a_plus = (np.min(h[:,0]), np.max(h[0,:]))
a_mus = (np.max(h[:,0]), np.min(h[0,:]))
a_plus


(1.090653684881621e-10, 1.090653684881621e-10)

In [69]:
a_mus

(0.01115044025450158, 8.961640037034365e-11)

In [70]:
d_plus = np.zeros(obj.shape[0])
d_mus = np.zeros(obj.shape[0])

In [71]:
for i in range(len(d_plus)):
    d_plus[i] = math.sqrt((a_plus[0]-h[i,0])**2+(a_plus[1]-h[i,1])**2)
    d_mus[i] = math.sqrt((a_mus[0]-h[i,0])**2+(a_mus[1]-h[i,1])**2)

In [72]:
T = np.zeros(obj.shape[0])
T = d_mus/(d_plus+d_mus)

In [73]:
T_MAX = max(T)
T_MIN = min(T)

In [74]:
t = (T-T_MIN)/(T_MAX-T_MIN)
t =  pd.DataFrame(t)
t.to_csv("./t_final.csv")

In [75]:
t = (T-T_MIN)/(T_MAX-T_MIN)
t

array([1.        , 0.75989317, 0.46536251, 0.83690608, 0.18690538,
       0.67886468, 0.89073095, 0.74695819, 0.97983662, 0.05007683,
       0.53664092, 0.57432952, 0.68571199, 0.45323363, 0.9595659 ,
       0.22594113, 0.02239243, 0.61332613, 0.28346366, 0.08961427,
       0.48356723, 0.16383576, 0.02864531, 0.32991268, 0.11252591,
       0.90396242, 0.26562571, 0.16836332, 0.08763224, 0.41147185,
       0.69210474, 0.63735545, 0.10659688, 0.        , 0.48960601,
       0.2042338 , 0.10434102, 0.03844037, 0.89131754, 0.58023519,
       0.11564502, 0.85601049, 0.56131303, 0.62697035, 0.86209509,
       0.64930678, 0.99328341, 0.77902828, 0.23748812, 0.08568035,
       0.45938221, 0.54955961, 0.50190635, 0.41741447, 0.15783882,
       0.85531404, 0.91977106, 0.23013299, 0.34854451, 0.75363369,
       0.09162017, 0.93715607, 0.33722269, 0.11015509, 0.58614502,
       0.10047026, 0.10835623, 0.17295711, 0.57897807, 0.36473267,
       0.23362502, 0.02346003, 0.77235507, 0.73474076, 0.26127

In [76]:
len(t[t>0.99])
t[t>0.99]
#0.99999889
#0.99994067

array([1.        , 0.99328341])

In [80]:
a1 =  obj[obj[:,0]<3.78]
a2 = a1[a1[:,1]>391]
print(a2.shape)
b1 = t[obj[:,0]<3.78]
b2 = b1[a1[:,1]>391].reshape(-1,1)
b2_max = max(b2)
b2_min = min(b2)
b2 = (b2-b2_min)/(b2_max-b2_min)
all = np.concatenate([a2,b2],axis=1)

(74, 2)


In [81]:
sort_index = np.argsort(all[:,-1])
sorted_all = all[sort_index]

In [82]:
sorted_all[sorted_all[:,-1]>0.9]

array([[  2.9777394 , 418.7341919 ,   0.90609826],
       [  2.96637803, 399.1016846 ,   0.95315419],
       [  2.96124713, 398.9570007 ,   0.96034947],
       [  2.9606973 , 397.9385376 ,   0.96280674],
       [  2.9482358 , 394.2416382 ,   0.98596258],
       [  2.94768578, 393.2844849 ,   0.98837009],
       [  2.94145504, 391.4428101 ,   1.        ]])

In [83]:
sorted_all[:,0] = (3.78-sorted_all[:,0])/3.78

In [84]:
sorted_all[:,1] = (sorted_all[:,1]-391)/391

In [85]:
sorted_all

array([[4.79021429e-04, 8.50936851e-01, 0.00000000e+00],
       [2.18136661e-02, 8.49560047e-01, 5.19952785e-02],
       [3.09711450e-02, 8.23525353e-01, 7.04517758e-02],
       [3.28026407e-02, 8.18224505e-01, 7.43141481e-02],
       [3.46341365e-02, 8.12897119e-01, 7.82361671e-02],
       [3.64656050e-02, 8.07472171e-01, 8.22054232e-02],
       [3.82971008e-02, 8.01990714e-01, 8.62309473e-02],
       [3.96870413e-02, 7.91454266e-01, 8.81988458e-02],
       [4.19600923e-02, 7.90762118e-01, 9.44383193e-02],
       [4.49606860e-02, 7.71651402e-01, 9.97178615e-02],
       [4.70129971e-02, 7.68297435e-01, 1.05088294e-01],
       [4.84028865e-02, 7.57352005e-01, 1.07377284e-01],
       [5.02343548e-02, 7.51421916e-01, 1.11841141e-01],
       [5.18450868e-02, 7.42878868e-01, 1.15322529e-01],
       [5.34557913e-02, 7.34304755e-01, 1.18882087e-01],
       [5.67575444e-02, 6.76026483e-01, 1.20530858e-01],
       [5.52872870e-02, 7.28293963e-01, 1.23573424e-01],
       [5.82603828e-02, 6.73736